#!/bin/bash

function install_ZSH_ROOT() {
    echo "install_ZSH_ROOT"
    sleep 10

    # BackUp .zshrc
    if mv -n /root/.zshrc /root/.zshrc-backup-$(date +"%Y-%m-%d"); then
        echo -e "Backed up the current .zshrc to .zshrc-backup-date\n"
    fi

    # Installing oh-my-zsh
    clear
    echo -e "Installing oh-my-zsh\n"

    if [ -d /root/.oh-my-zsh ]; then
        echo -e "oh-my-zsh is already installed\n"
        sudo git -C /root/.oh-my-zsh remote set-url origin https://github.com/ohmyzsh/ohmyzsh.git
    else
        sudo git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git /root/.oh-my-zsh
    fi
    sleep 5

    # dotfiles
    clear
    sudo cp -f "${dir}/../dotfiles/.zshrc" /root/
    sudo mkdir -p /root/.cache/zsh/

    if [ -f /root/.zcompdump ]; then
        sudo mv /root/.zcompdump* /root/.cache/zsh/
    fi
    sleep 5

    # Plugins
    clear
    plugins=(
        "zsh-exa:https://github.com/ptavares/zsh-exa.git"
        "zsh-autopair:https://github.com/hlissner/zsh-autopair"
        "zsh-autosuggestions:https://github.com/zsh-users/zsh-autosuggestions"
        "zsh-completions:https://github.com/zsh-users/zsh-completions"
        "zsh-history-substring-search:https://github.com/zsh-users/zsh-history-substring-search"
        "zsh-syntax-highlighting:https://github.com/zsh-users/zsh-syntax-highlighting.git"
        "you-should-use:https://github.com/MichaelAquilina/zsh-you-should-use.git"
        "fzf-tab:https://github.com/Aloxaf/fzf-tab"
    )

    for plugin in "${plugins[@]}"; do
        plugin_name=$(echo "$plugin" | cut -d":" -f1)
        plugin_url=$(echo "$plugin" | cut -d":" -f2)

        if [ -d "/root/.oh-my-zsh/custom/plugins/$plugin_name" ]; then
            cd "/root/.oh-my-zsh/custom/plugins/$plugin_name" && git pull
        else
            sudo git clone --depth=1 "$plugin_url" "/root/.oh-my-zsh/custom/plugins/$plugin_name"
        fi
    done

    sleep 5

    # STARSHIP
    clear
    echo -e "Root: STARSHIP"
    sudo wget https://starship.rs/install.sh
    sudo chmod +x install.sh
    sudo sh ./install.sh
    sudo wget https://raw.githubusercontent.com/gabrielomana/MyStarships/main/starship_1.toml -O /root/.config/starship.toml
    sleep 5

    # REBOOT ZSH
    sudo su - -c "chsh -s /bin/zsh root"
}

function install_ZSH() {
    clear

    # Install ZSH
    if command -v zsh &> /dev/null && command -v git &> /dev/null && command -v wget &> /dev/null; then
        echo -e "ZSH, Git, and wget are already installed\n"
    else
        if sudo nala install zsh git wget -y || sudo pacman -S zsh git wget || sudo dnf install -y zsh git wget || sudo yum install -y zsh git wget || sudo brew install git zsh wget || pkg install git zsh wget ; then
            echo -e "zsh, wget, and git Installed\n"
        else
            echo -e "Please install the following packages first, then try again: zsh git wget \n" && exit
        fi
    fi

    # BackUp .zshrc
    if mv -n ~/.zshrc ~/.zshrc-backup-$(date +"%Y-%m-%d"); then
        echo -e "Backed up the current .zshrc to .zshrc-backup-date\n"
    fi

    # Installing oh-my-zsh
    clear
    if [ -d ~/.oh-my-zsh ]; then
        echo -e "oh-my-zsh is already installed\n"
        git -C ~/.oh-my-zsh remote set-url origin https://github.com/ohmyzsh/ohmyzsh.git
    else
        git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
    fi
    sleep 5

    # dotfiles
    clear
    cp -f ../dotfiles/.zshrc ~/
    mkdir -p ~/.cache/zsh/

    if [ -f ~/.zcompdump ]; then
        mv ~/.zcompdump* ~/.cache/zsh/
    fi
    sleep 5

    # Plugins
    clear
    plugins=(
        "zsh-exa:https://github.com/ptavares/zsh-exa.git"
        "zsh-autopair:https://github.com/hlissner/zsh-autopair"
        "zsh-autosuggestions:https://github.com/zsh-users/zsh-autosuggestions"
        "zsh-completions:https://github.com/zsh-users/zsh-completions"
        "zsh-history-substring-search:https://github.com/zsh-users/zsh-history-substring-search"
        "zsh-syntax-highlighting:https://github.com/zsh-users/zsh-syntax-highlighting.git"
        "you-should-use:https://github.com/MichaelAquilina/zsh-you-should-use.git"
        "fzf-tab:https://github.com/Aloxaf/fzf-tab"
    )

    for plugin in "${plugins[@]}"; do
        plugin_name=$(echo "$plugin" | cut -d":" -f1)
        plugin_url=$(echo "$plugin" | cut -d":" -f2)

        if [ -d "~/.oh-my-zsh/custom/plugins/$plugin_name" ]; then
            cd "~/.oh-my-zsh/custom/plugins/$plugin_name" && git pull
        else
            git clone --depth=1 "$plugin_url" "~/.oh-my-zsh/custom/plugins/$plugin_name"
        fi
    done

    sleep 5

    # STARSHIP
    clear
    curl -sS https://starship.rs/install.sh | sh
    wget https://raw.githubusercontent.com/gabrielomana/MyStarships/main/starship_1.toml -O ~/.config/starship.toml
    sleep 5

    # REBOOT ZSH
    clear
    echo -e "\nSudo access is needed to change default shell\n"
    if chsh -s "$(which zsh)" && /bin/zsh -i -c 'omz update'; then
        echo "ZSH in user: OK"
        echo "installing ZSH in root..."
        sleep 3
        install_ZSH_ROOT
    else
        echo -e "Something is wrong"
    fi
    return
}
