#!/bin/bash
function check_uninstalled() {
  local package
  list=""

  while read -r package; do
    [ -z "$package" ] && continue

    if dnf list installed "$package" >/dev/null 2>&1; then
      list+=" $package"
    fi
  done < "$1"

  if [ -n "$list" ]; then
    sudo dnf remove -y $list
    sudo dnf autoremove -y
    sudo dnf install -f
    sudo dnf clean all
    clear
  else
    clear
    echo "No packages to remove."
  fi
}

# Usage example:
# check_uninstalled "package_list.txt"


function check_installed() {
 # Parámetros y archivo de salida
    list_file="$1"

    # Verificar si el archivo de lista existe
    if [ ! -f "$list_file" ]; then
        echo "El archivo de lista '$list_file' no existe."
        exit 1
    fi
    packages=()
    # Leer Cada Línea del Archivo de Lista
    while read -r line; do
        # Limpiar la Línea de Espacios en Blanco
        line=$(echo "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
        packages+=("$line")
    done < "$list_file"

   # Instalar grupos y paquetes si hay elementos en los arreglos
    c="sudo dnf install -y --skip-broken ${packages[@]}"
      echo $c
      sleep 3
      eval $c
}

function add_extra_repos(){

##EXTRA REPOS
sudo dnf -y copr enable refi64/webapp-manager
sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

curl -1sLf \
   'https://dl.cloudsmith.io/public/balena/etcher/setup.rpm.sh' \
   | sudo -E bash

sudo yum -y install https://download.onlyoffice.com/repo/centos/main/noarch/onlyoffice-repo.noarch.rpm
sudo dnf -y copr enable ayoungdukie/Personal_Repo

sudo rpm --import https://raw.githubusercontent.com/UnitedRPMs/unitedrpms/master/URPMS-GPG-PUBLICKEY-Fedora
sudo dnf -y install https://github.com/UnitedRPMs/unitedrpms/releases/download/20/unitedrpms-$(rpm -E %fedora)-20.fc$(rpm -E %fedora).noarch.rpm

sudo dnf makecache --refresh

}

function install_kde {
  echo "INSTALL KDE PLASMA: "
  echo " - Install KDE Plasma Core"
  check_installed "${kde_plasma}"
  sudo systemctl enable sddm
  sudo systemctl set-default graphical.target
  echo "$(cat /etc/sddm.conf | sed -E s/'^\#?Numlock\=.*$'/'Numlock=on'/)" | sudo tee /etc/sddm.conf && sudo systemctl daemon-reload
  sleep 3

  #CLEAN PLASMA
  clear
  check_uninstalled "${kde_bloatware}"
  sleep 7

  #KDE'S apps
  clear
  echo "INSTALL KDE PLASMA: "
  echo " - Install KDEL Plasma Core"
  echo " - Remove apps and bloatware"
  echo " - Install KDE's APPS"
  sleep 3
  check_installed "${kde_plasma_apps}"
}

function hardware-settings {
  # Obtener el nombre del fabricante de la GPU.
  gpu_vendor=$(lspci | grep -i "3D controller" | awk '{print $3}')
  sudo dnf install -y ffmpeg ffmpeg-libs libva libva-utils
  sudo dnf config-manager --set-enabled fedora-cisco-openh264
  sudo dnf install -y openh264 gstreamer1-plugin-openh264 mozilla-openh264

  # Instalar los controladores de la GPU.
  case "$gpu_vendor" in
    Intel*)
      echo "Instalando controladores para la GPU Intel..."
      sudo dnf install -y vdpau-driver-all intel-media-driver
      ;;
    AMD*)
      echo "Instalando controladores para la GPU AMD..."
      sudo dnf install -y akmod-amdgpu radeon-profile vdpau-driver-all amdgpu-pro
      sudo dnf swap mesa-va-drivers mesa-va-drivers-freeworld
      sudo dnf swap mesa-vdpau-drivers mesa-vdpau-drivers-freeworld
      ;;
    NVIDIA*)
      echo "Instalando controladores para la GPU NVIDIA..."
      sudo dnf install -y akmod-nvidia nvidia-driver nvidia-settings nvidia-xconfig vdpau-driver-all
      sudo dnf install -y nvidia-vaapi-driver
      sudo grubby --update-kernel=ALL --args="nvidia-drm.modeset=1"
      ;;
  esac

  # Verificar que la aceleración de hardware esté instalada correctamente.
  for api in vaapi vdpau; do
    echo "Verificando $api"
    if ! command -v $api-info &> /dev/null; then
      echo "$api no está instalado."
    fi
    echo "$api está instalado."
  done

  # Configuración del procesador
  # Obtener el nombre del procesador.
  cpu_name=$(lscpu | grep -Ei "Model name|Nombre del modelo" | awk '{print $0}')

  # Instalar los controladores y microcódigos apropiados.
  if echo "$cpu_name" | grep -qi "intel"; then
    echo "Instalando controladores y microcódigos para el procesador Intel..."
    sudo dnf install --enablerepo=rpmfusion-nonfree akmod-intel-ucode intel-microcode
  elif echo "$cpu_name" | grep -qi "amd"; then
    echo "Instalando controladores y microcódigos para el procesador AMD..."
    sudo dnf install --enablerepo=rpmfusion-nonfree akmod-amd-ucode amd-microcode
  else
    echo "No se pudo identificar el procesador."
  fi

  # Verificar si la máquina es un host de máquinas virtuales.
  if [[ "$(cat /sys/class/dmi/id/chassis_type)" != "Machine" && "$(cat /sys/class/dmi/id/chassis_type)" != "Maquina" ]]; then
    # Estamos en una máquina física
    echo "Máquina física detectada."
  else
    # Estamos en una máquina virtual

    # Identificar el hypervisor
    hypervisor=$(cat /sys/class/dmi/id/product_name)

    case "$hypervisor" in
      VMware*)
        echo "Instalando controladores para VMware..."
        sudo dnf install --enablerepo=rpmfusion-nonfree open-vm-tools
        ;;
      Microsoft*)
        echo "Instalando controladores para Microsoft Hyper-V..."
        sudo dnf install --enablerepo=rpmfusion-nonfree hyperv-tools
        ;;
      VirtualBox*)
        echo "Instalando controladores para VirtualBox..."
        sudo dnf install --enablerepo=rpmfusion-nonfree VirtualBox-guest-additions-iso
        sudo mount /dev/cdrom /mnt/cdrom
        sudo ./VBoxLinuxAdditions.run
        sudo umount /mnt/cdrom
        ;;
      KVM*)
        echo "Instalando controladores para KVM..."
        sudo dnf install --enablerepo=rpmfusion-nonfree libvirt-guest-tools
        ;;
      *)
        echo "Hypervisor no reconocido: $hypervisor"
        ;;
    esac
  fi
}

function install_core_apps() {
  # Herramientas y bibliotecas de desarrollo
  sudo dnf install -y npm
  sudo npm install -g electron-store
  sudo dnf install -y python3-pip

  # Instalación de Rust
  sudo wget https://sh.rustup.rs -O rustup-init.sh
  sudo chmod +x rustup-init.sh
  ./rustup-init.sh -y
  source "$HOME/.cargo/env"
  sudo rm rustup-init.sh -rf

  # Actualizar variables de entorno de Rust
  source "$HOME/.cargo/env"
  source "$HOME/.profile"
  source "$HOME/.cargo/env"

  # Codecs y controladores
  clear
  echo "INSTALAR APLICACIONES BÁSICAS DEL SISTEMA:"
  echo " - Herramientas y bibliotecas de desarrollo"
  echo " - Codecs y controladores"
  sleep 3

  # Instalación y actualización de grupos de paquetes
  sudo dnf -y group install "C Development Tools and Libraries" "Development Tools"
  sudo dnf -y groupupdate multimedia sound-and-video core --exclude=zram* --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin --allowerasing && sync
  sudo dnf swap 'ffmpeg-free' 'ffmpeg' --allowerasing

  # Instalación adicional de paquetes
  sudo dnf install gstreamer1-plugins-{bad-\*,good-\*,base} gstreamer1-plugin-openh264 gstreamer1-libav --exclude=gstreamer1-plugins-bad-free-devel ffmpeg gstreamer-ffmpeg
  sudo dnf install lame\* --exclude=lame-devel
  sudo dnf group upgrade --with-optional Multimedia

  check_installed "${codecs}"

  # Utilidades
  clear
  echo "INSTALAR APLICACIONES BÁSICAS DEL SISTEMA:"
  echo " - Herramientas y bibliotecas de desarrollo"
  echo " - Codecs y controladores"
  echo " - Utilidades"
  sleep 3
  check_installed "${utilities}"

  numlockx on
  sudo numlockx on
  sudo sed -i 's/^\#?Numlock\=.*$/Numlock=on/' /etc/sddm.conf
  sudo systemctl daemon-reload
  sudo dnf copr enable atim/ubuntu-fonts -y && sudo dnf install -y ubuntu-family-fonts
  sudo fc-cache -fv
  sudo dnf swap ffmpeg-free ffmpeg --allowerasing

  cargo install cargo-update topgrade eza

  # Definir nuevos alias
  new_aliases="# Alias adicionales
  alias cat=\"batcat -f\"
  alias ocat=\"/usr/bin/cat\"
  alias fupdate=\"topgrade && sudo hblock -O /etc/host\"
  alias l=\"eza\"
  alias lastversion=\"~/.local/pipx/venvs/lastversion/bin/./lastversion\"
  alias kedit=\"/usr/bin/featherpad\"
  alias ytmdesktop=\"/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=start-ytmdesktop.sh --file-forwarding app.ytmdesktop.ytmdesktop\"

  function ls() {
    if [[ \$# -eq 0 ]]; then
      # Si no hay argumentos, ejecuta eza con los sufijos adicionales
      eza --group-directories-first --icons
    else
      case \$1 in
        ls) shift; eza \$@ --group-directories-first --icons;;
        ll) shift; eza \$@ -lbGFhmua --group-directories-first --no-permissions --icons;;
        llp) shift; eza \$@ -lbGFhmua --group-directories-first --icons;;
        la) shift; eza \$@ -a --group-directories-first --icons;;
        lt) shift; eza \$@ --tree --level=2 --icons;;
        lt3) shift; eza \$@ --tree --level=3 --icons;;
        lt4) shift; eza \$@ --tree --level=4 --icons;;
        *)
          # Agregamos la opción --color solo si es un terminal interactivo
          if [ -t 1 ]; then
            eza \$@ --group-directories-first --icons --color
          else
            eza \$@ --group-directories-first --icons
          fi
          ;;
      esac
    fi
  }"

  # Agregar nuevos alias al final del archivo .bashrc
  echo -e "$new_aliases" >> ~/.bashrc
  echo -e "$new_aliases" | sudo tee -a /root/.bashrc

  echo -e "export PATH=$HOME/.cargo/bin:/usr/local/bin:$PATH" | sudo tee -a ~/.bashrc
  echo -e "export PATH=$HOME/.cargo/bin:/usr/local/bin:$PATH" | sudo tee -a /root/.bashrc

  hardware-settings

  # Nerd Fonts
  clear
  echo "INSTALAR APLICACIONES BÁSICAS DEL SISTEMA:"
  echo " - Herramientas y bibliotecas de desarrollo"
  echo " - Codecs y controladores"
  echo " - Utilidades"
  echo " - Pipewire y Wireplumber"
  echo " - Nerd Fonts"
  sleep 3

  # Directorio temporal para descargar fuentes
  temp_dir="/tmp/nerd_fonts"
  # Crear directorio temporal si no existe
  mkdir -p "$temp_dir"

  # Obtener URLs de descarga para las versiones más recientes
  font_names=("JetBrainsMono" "Ubuntu" "Mononoki" "Hack")
  for font_name in "${font_names[@]}"; do
    latest_release_url="https://github.com/ryanoasis/nerd-fonts/releases/latest"
    font_download_url=$(curl -sL -I -o /dev/null -w '%{url_effective}' "$latest_release_url" | sed "s/tag/download/")"/$font_name.zip"
    # Descargar la fuente
    wget -O "$temp_dir/$font_name.zip" "$font_download_url"
    # Descomprimir la fuente
    sudo unzip "$temp_dir/$font_name.zip" -d "$temp_dir/$font_name"
  done

  # Directorio de instalación de fuentes en el sistema
  install_dir="/usr/share/fonts/nerd_fonts"
  # Crear directorio de instalación si no existe
  sudo mkdir -p "$install_dir"
  # Mover fuentes al directorio de instalación
  for font_name in "${font_names[@]}"; do
    sudo mv "$temp_dir/$font_name"/*.{ttf,otf} "$install_dir"
  done

  # Limpieza: Eliminar directorio temporal
  sudo rm -rf "$temp_dir"

  # Instalar emojis a color
  sudo dnf install -y fonts-noto-color-emoji
  # Copiar configuración de fuentes
  sudo cp dotfiles/fonts.conf /etc/fonts/fonts.conf -rf
  # Actualizar la caché de fuentes
  fc-cache -f -v
}


#MULTIMEDIA
function install_multimedia()
{
clear
echo -e "INSTALL MULTIMEDIA APPS: \n"
sleep 3
check_installed "${multimedia}"
}

#EXTRA APPS
function install_extra_apps()
{
clear
a=0
f=0
while [ $a -lt 1 ]
do
        read -p "Do you wish to install Extra APPS? " yn
        case $yn in
            [Yy]* ) a=1;add_extra_repos;check_installed "${exta_apps}";f=1;clear;;
            [Nn]* ) a=1;echo "OK";clear;;
            * ) echo "Please answer yes or no.";;
        esac
    done

sudo systemctl start libvirtd
sudo systemctl enable libvirtd

clear
    if [ $f == 1 ]; then

      sudo cargo install cargo-update
      sudo timedatectl set-local-rtc 1
      sudo systemctl start libvirtd
      sudo systemctl enable libvirtd

      #FONTS
      sudo rpm -i https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm
      sudo dnf install -y curl cabextract xorg-x11-font-utils fontconfig
      sudo dnf install -y dejavu-fonts* google-roboto-fonts
      sudo fc-cache -fv

      #OnlyOffice
      sudo yum install onlyoffice-desktopeditors -y


      #flatpak
#         flatpak install -y flathub app.ytmdesktop.ytmdesktop
#         flatpak install -y flathub tv.kodi.Kodi
#         flatpak install -y flathub io.github.mimbrero.WhatsAppDesktop
#         flatpak install -y flathub io.freetubeapp.FreeTube
#         flatpak install -y flathub com.github.tenderowl.frog
#         flatpak install -y flathub com.github.vkohaupt.vokoscreenNG
#         flatpak install -y flathub org.phoenicis.playonlinux
#         flatpak install -y flathub com.usebottles.bottles
#         flatpak install -y flathub us.zoom.Zoom
#         flatpak install -y flathub com.anydesk.Anydesk
#         flatpak install -y flathub com.microsoft.Teams
#         flatpak install -y flathub com.github.bajoja.indicator-kdeconnect

      #OTHERS

  fi
return
}

