color_theme = "TTY"
update_ms = 1500
proc_sorting = "cpu lazy"
proc_reversed = false
proc_tree = true
check_temp = true
cpu_invert_lower = true
cpu_single_graph = false
show_uptime = true
selected_name = ""
