#!/bin/bash

# Instalar Zsh, Git y wget si no están instalados
sudo apt update
sudo apt install -y zsh git wget

# Respaldar el archivo .zshrc actual
backup_file() {
    local file="$1"
    if [ -f "$file" ]; then
        mv -n "$file" "$file-backup-$(date +"%Y-%m-%d")"
        echo "Backed up $file to $file-backup-$(date +"%Y-%m-%d")"
    fi
}

# Instalar oh-my-zsh
install_oh_my_zsh() {
    local user="$1"
    local oh_my_zsh_dir="/home/$user/.oh-my-zsh"

    if [ -d "$oh_my_zsh_dir" ]; then
        echo "oh-my-zsh is already installed for $user"
        sudo -u "$user" git -C "$oh_my_zsh_dir" remote set-url origin https://github.com/ohmyzsh/ohmyzsh.git
    else
        sudo -u "$user" git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git "$oh_my_zsh_dir"
    fi
}

# Copiar la configuración personalizada
copy_config() {
    local user="$1"
    local dotfiles_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../dotfiles"
    sudo -u "$user" cp -f "$dotfiles_dir/.zshrc" "/home/$user/"
    sudo -u "$user" mkdir -p "/home/$user/.cache/zsh/"
    sudo -u "$user" mv "/home/$user/.zcompdump"* "/home/$user/.cache/zsh/"
}

# Configurar plugins de oh-my-zsh
configure_plugins() {
    local user="$1"
    local plugins=("zsh-exa" "zsh-autopair" "zsh-autosuggestions" "zsh-completions" "zsh-history-substring-search" "zsh-syntax-highlighting" "you-should-use" "fzf-tab")

    for plugin in "${plugins[@]}"; do
        local plugin_dir="/home/$user/.oh-my-zsh/custom/plugins/$plugin"
        if [ -d "$plugin_dir" ]; then
            sudo -u "$user" git -C "$plugin_dir" pull
        else
            sudo -u "$user" git clone --depth=1 "https://github.com/$plugin" "$plugin_dir"
        fi
    done
}

# Instalar fzf
sudo apt install -y fzf

# Configurar Starship
configure_starship() {
    local user="$1"
    sudo -u "$user" sh -c "$(curl -fsSL https://starship.rs/install.sh)"
    sudo -u "$user" wget -O "/home/$user/.config/starship.toml" https://raw.githubusercontent.com/gabrielomana/MyStarships/main/starship_1.toml
}

# Cambiar la shell predeterminada a Zsh
change_default_shell() {
    local user="$1"
    sudo chsh -s "$(which zsh)" "$user"
}

# Instalación para el usuario actual
install_ZSH() {
    backup_file "$HOME/.zshrc"
    install_oh_my_zsh "$USER"
    copy_config "$USER"
    configure_plugins "$USER"
    configure_starship "$USER"
    change_default_shell "$USER"
}

# Instalación para el usuario root
install_ZSH_ROOT() {
    backup_file "/root/.zshrc"
    install_oh_my_zsh "root"
    copy_config "root"
    configure_plugins "root"
    configure_starship "root"
    change_default_shell "root"
}

# Ejecutar instalaciones
install_ZSH
install_ZSH_ROOT

echo "Zsh y oh-my-zsh instalados y configurados correctamente."